# Generated by Django 5.0.2 on 2024-03-12 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloguser',
            old_name='is_aurhor',
            new_name='is_author',
        ),
    ]
