# Generated by Django 5.0.2 on 2024-03-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mashapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create',
            name='is_active',
        ),
        migrations.AddField(
            model_name='tag',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
