# Generated by Django 5.0.2 on 2024-03-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mashapp', '0002_remove_create_is_active_tag_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='create',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
